/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package science.platform.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the SpAffiliation service. Represents a row in the &quot;SciencePlatformHook_SpAffiliation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link science.platform.model.impl.SpAffiliationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link science.platform.model.impl.SpAffiliationImpl}.
 * </p>
 *
 * @author Jerry h. Seo
 * @see SpAffiliation
 * @see science.platform.model.impl.SpAffiliationImpl
 * @see science.platform.model.impl.SpAffiliationModelImpl
 * @generated
 */
public interface SpAffiliationModel extends BaseModel<SpAffiliation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sp affiliation model instance should use the {@link SpAffiliation} interface instead.
	 */

	/**
	 * Returns the primary key of this sp affiliation.
	 *
	 * @return the primary key of this sp affiliation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sp affiliation.
	 *
	 * @param primaryKey the primary key of this sp affiliation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp affiliation ID of this sp affiliation.
	 *
	 * @return the sp affiliation ID of this sp affiliation
	 */
	public long getSpAffiliationId();

	/**
	 * Sets the sp affiliation ID of this sp affiliation.
	 *
	 * @param spAffiliationId the sp affiliation ID of this sp affiliation
	 */
	public void setSpAffiliationId(long spAffiliationId);

	/**
	 * Returns the sp region ID of this sp affiliation.
	 *
	 * @return the sp region ID of this sp affiliation
	 */
	public long getSpRegionId();

	/**
	 * Sets the sp region ID of this sp affiliation.
	 *
	 * @param spRegionId the sp region ID of this sp affiliation
	 */
	public void setSpRegionId(long spRegionId);

	/**
	 * Returns the sp country ID of this sp affiliation.
	 *
	 * @return the sp country ID of this sp affiliation
	 */
	public long getSpCountryId();

	/**
	 * Sets the sp country ID of this sp affiliation.
	 *
	 * @param spCountryId the sp country ID of this sp affiliation
	 */
	public void setSpCountryId(long spCountryId);

	/**
	 * Returns the sp affiliation code of this sp affiliation.
	 *
	 * @return the sp affiliation code of this sp affiliation
	 */
	@AutoEscape
	public String getSpAffiliationCode();

	/**
	 * Sets the sp affiliation code of this sp affiliation.
	 *
	 * @param spAffiliationCode the sp affiliation code of this sp affiliation
	 */
	public void setSpAffiliationCode(String spAffiliationCode);

	/**
	 * Returns the sp affiliation name of this sp affiliation.
	 *
	 * @return the sp affiliation name of this sp affiliation
	 */
	public String getSpAffiliationName();

	/**
	 * Returns the localized sp affiliation name of this sp affiliation in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized sp affiliation name of this sp affiliation
	 */
	@AutoEscape
	public String getSpAffiliationName(Locale locale);

	/**
	 * Returns the localized sp affiliation name of this sp affiliation in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized sp affiliation name of this sp affiliation. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getSpAffiliationName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized sp affiliation name of this sp affiliation in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized sp affiliation name of this sp affiliation
	 */
	@AutoEscape
	public String getSpAffiliationName(String languageId);

	/**
	 * Returns the localized sp affiliation name of this sp affiliation in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized sp affiliation name of this sp affiliation
	 */
	@AutoEscape
	public String getSpAffiliationName(String languageId, boolean useDefault);

	@AutoEscape
	public String getSpAffiliationNameCurrentLanguageId();

	@AutoEscape
	public String getSpAffiliationNameCurrentValue();

	/**
	 * Returns a map of the locales and localized sp affiliation names of this sp affiliation.
	 *
	 * @return the locales and localized sp affiliation names of this sp affiliation
	 */
	public Map<Locale, String> getSpAffiliationNameMap();

	/**
	 * Sets the sp affiliation name of this sp affiliation.
	 *
	 * @param spAffiliationName the sp affiliation name of this sp affiliation
	 */
	public void setSpAffiliationName(String spAffiliationName);

	/**
	 * Sets the localized sp affiliation name of this sp affiliation in the language.
	 *
	 * @param spAffiliationName the localized sp affiliation name of this sp affiliation
	 * @param locale the locale of the language
	 */
	public void setSpAffiliationName(String spAffiliationName, Locale locale);

	/**
	 * Sets the localized sp affiliation name of this sp affiliation in the language, and sets the default locale.
	 *
	 * @param spAffiliationName the localized sp affiliation name of this sp affiliation
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setSpAffiliationName(String spAffiliationName, Locale locale,
		Locale defaultLocale);

	public void setSpAffiliationNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized sp affiliation names of this sp affiliation from the map of locales and localized sp affiliation names.
	 *
	 * @param spAffiliationNameMap the locales and localized sp affiliation names of this sp affiliation
	 */
	public void setSpAffiliationNameMap(
		Map<Locale, String> spAffiliationNameMap);

	/**
	 * Sets the localized sp affiliation names of this sp affiliation from the map of locales and localized sp affiliation names, and sets the default locale.
	 *
	 * @param spAffiliationNameMap the locales and localized sp affiliation names of this sp affiliation
	 * @param defaultLocale the default locale
	 */
	public void setSpAffiliationNameMap(
		Map<Locale, String> spAffiliationNameMap, Locale defaultLocale);

	/**
	 * Returns the sp active of this sp affiliation.
	 *
	 * @return the sp active of this sp affiliation
	 */
	public boolean getSpActive();

	/**
	 * Returns <code>true</code> if this sp affiliation is sp active.
	 *
	 * @return <code>true</code> if this sp affiliation is sp active; <code>false</code> otherwise
	 */
	public boolean isSpActive();

	/**
	 * Sets whether this sp affiliation is sp active.
	 *
	 * @param spActive the sp active of this sp affiliation
	 */
	public void setSpActive(boolean spActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(science.platform.model.SpAffiliation spAffiliation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<science.platform.model.SpAffiliation> toCacheModel();

	@Override
	public science.platform.model.SpAffiliation toEscapedModel();

	@Override
	public science.platform.model.SpAffiliation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}