/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package science.platform.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the SpDomain service. Represents a row in the &quot;SciencePlatformHook_SpDomain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link science.platform.model.impl.SpDomainModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link science.platform.model.impl.SpDomainImpl}.
 * </p>
 *
 * @author Jerry h. Seo
 * @see SpDomain
 * @see science.platform.model.impl.SpDomainImpl
 * @see science.platform.model.impl.SpDomainModelImpl
 * @generated
 */
public interface SpDomainModel extends BaseModel<SpDomain> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sp domain model instance should use the {@link SpDomain} interface instead.
	 */

	/**
	 * Returns the primary key of this sp domain.
	 *
	 * @return the primary key of this sp domain
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sp domain.
	 *
	 * @param primaryKey the primary key of this sp domain
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp domain ID of this sp domain.
	 *
	 * @return the sp domain ID of this sp domain
	 */
	public long getSpDomainId();

	/**
	 * Sets the sp domain ID of this sp domain.
	 *
	 * @param spDomainId the sp domain ID of this sp domain
	 */
	public void setSpDomainId(long spDomainId);

	/**
	 * Returns the sp domain code of this sp domain.
	 *
	 * @return the sp domain code of this sp domain
	 */
	@AutoEscape
	public String getSpDomainCode();

	/**
	 * Sets the sp domain code of this sp domain.
	 *
	 * @param spDomainCode the sp domain code of this sp domain
	 */
	public void setSpDomainCode(String spDomainCode);

	/**
	 * Returns the sp domain name of this sp domain.
	 *
	 * @return the sp domain name of this sp domain
	 */
	public String getSpDomainName();

	/**
	 * Returns the localized sp domain name of this sp domain in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized sp domain name of this sp domain
	 */
	@AutoEscape
	public String getSpDomainName(Locale locale);

	/**
	 * Returns the localized sp domain name of this sp domain in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized sp domain name of this sp domain. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getSpDomainName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized sp domain name of this sp domain in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized sp domain name of this sp domain
	 */
	@AutoEscape
	public String getSpDomainName(String languageId);

	/**
	 * Returns the localized sp domain name of this sp domain in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized sp domain name of this sp domain
	 */
	@AutoEscape
	public String getSpDomainName(String languageId, boolean useDefault);

	@AutoEscape
	public String getSpDomainNameCurrentLanguageId();

	@AutoEscape
	public String getSpDomainNameCurrentValue();

	/**
	 * Returns a map of the locales and localized sp domain names of this sp domain.
	 *
	 * @return the locales and localized sp domain names of this sp domain
	 */
	public Map<Locale, String> getSpDomainNameMap();

	/**
	 * Sets the sp domain name of this sp domain.
	 *
	 * @param spDomainName the sp domain name of this sp domain
	 */
	public void setSpDomainName(String spDomainName);

	/**
	 * Sets the localized sp domain name of this sp domain in the language.
	 *
	 * @param spDomainName the localized sp domain name of this sp domain
	 * @param locale the locale of the language
	 */
	public void setSpDomainName(String spDomainName, Locale locale);

	/**
	 * Sets the localized sp domain name of this sp domain in the language, and sets the default locale.
	 *
	 * @param spDomainName the localized sp domain name of this sp domain
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setSpDomainName(String spDomainName, Locale locale,
		Locale defaultLocale);

	public void setSpDomainNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized sp domain names of this sp domain from the map of locales and localized sp domain names.
	 *
	 * @param spDomainNameMap the locales and localized sp domain names of this sp domain
	 */
	public void setSpDomainNameMap(Map<Locale, String> spDomainNameMap);

	/**
	 * Sets the localized sp domain names of this sp domain from the map of locales and localized sp domain names, and sets the default locale.
	 *
	 * @param spDomainNameMap the locales and localized sp domain names of this sp domain
	 * @param defaultLocale the default locale
	 */
	public void setSpDomainNameMap(Map<Locale, String> spDomainNameMap,
		Locale defaultLocale);

	/**
	 * Returns the sp active of this sp domain.
	 *
	 * @return the sp active of this sp domain
	 */
	public boolean getSpActive();

	/**
	 * Returns <code>true</code> if this sp domain is sp active.
	 *
	 * @return <code>true</code> if this sp domain is sp active; <code>false</code> otherwise
	 */
	public boolean isSpActive();

	/**
	 * Sets whether this sp domain is sp active.
	 *
	 * @param spActive the sp active of this sp domain
	 */
	public void setSpActive(boolean spActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(science.platform.model.SpDomain spDomain);

	@Override
	public int hashCode();

	@Override
	public CacheModel<science.platform.model.SpDomain> toCacheModel();

	@Override
	public science.platform.model.SpDomain toEscapedModel();

	@Override
	public science.platform.model.SpDomain toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}